### ISSUE TITLE
Either missing test files or files named wrong

### ISSUE THREAD

**Issue by DuarteCruz6** [SkyDev125/po_proj_tests_2024_2025#1]
I saw that while running the .sh, it says Total tests = 18 altought the last file is test 24. 

There are no tests number:
- 6
- 11
- 12
- 19 
- 20
- 21

PS.: Thanks for making extra tests!

**Comment by SkyDev125** [comment]
Those missing tests are probably the next tests that the teacher will run in the final project delivery.

I've added some extra tests of my own and hope they are helpfull!

**Comment by DuarteCruz6** [comment]
Thanks, I'll make sure to run them then :)
